version: "3.7"
networks:
  services-network:
services:
  postgresService:
    networks:
      - services-network
    image: postgres:latest
    container_name: postgres
    volumes:
      - .:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=1100
      - POSTGRES_USER=taradaszje
      - POSTGRES_DB=inteca_work
    restart: unless-stopped
  # EUREKA SERVER#####
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    networks:
      - services-network
    ports:
      - 8761:8761
    restart: unless-stopped
  # API GATEWAY######
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    networks:
      - services-network
    ports:
    - 8080:8080
    restart: unless-stopped
  # APPS*****************************************
  credit-service:
    image: credit-service:latest
    container_name: credit-service
    networks:
      - services-network
    ports:
      - 8060:8060
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresService/inteca_work
      - SPRING_DATASOURCE_USERNAME=taradaszje
      - SPRING_DATASOURCE_PASSWORD=1100
    restart: unless-stopped

  product-service:
    image: product-service:latest
    networks:
      - services-network
    container_name: product-service
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresService/inteca_work
      - SPRING_DATASOURCE_USERNAME=taradaszje
      - SPRING_DATASOURCE_PASSWORD=1100
    restart: unless-stopped

  customer-service:
    image: customer-service:latest
    networks:
      - services-network
    container_name: customer-service
    ports:
      - 8070:8070
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresService/inteca_work
      - SPRING_DATASOURCE_USERNAME=taradaszje
      - SPRING_DATASOURCE_PASSWORD=1100
    restart: unless-stopped
