server:
  port: 8080

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      routes:
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/cs/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/ps/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
