server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  ## PostgreSQL
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inteca_work
    username: taradaszje
    password: 1100
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true